server.port: ${DISCOVERY_PORT:8761}
spring.application.name: eureka-discovery-mimir
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}