server.port: ${PORT:0}
spring:
  application:
    name: mimir-users
    instance_id: ${INSTANCE_ID:${random.value}}
eureka:
  client.serviceUrl.defaultZone: http://localhost:8010/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id}