server.port: 0
spring:
  application:
    name: mimir-users
    instance_id: ${INSTANCE_ID:${random.value}}
  h2.console:
    enabled: true
    settings.web-allow-others: false # Allows connection via the API Gateway
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client.serviceUrl.defaultZone: http://localhost:${EUREKA_PORT:8010}/eureka
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id}