server.port: ${EUREKA_PORT:8010}
spring.application.name: eureka-discovery-mimir
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://localhost:${server.port}/eureka
  instance:
    preferIpAddress: true