server.port: 0

spring:
  application:
    name: mimir-account-management
    instance_id: ${INSTANCE_ID:${random.value}}
eureka:
  client.serviceUrl.defaultZone: http://localhost:${DISCOVERY_PORT:8010}/eureka
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id}