server.port: 0
spring:
  application:
    name: MimirUsers-Server-V0
    instance_id: ${INSTANCE_ID:${random.value}}
  h2.console:
    enabled: true
    settings.web-allow-others: true # Allows connection via the API Gateway
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost} # localhost = 127.0.0.1
    instanceId: ${spring.application.name}:${spring.application.instance_id}
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

gateway.ip: ${GATEWAY_IP:localhost}