server.port: ${API_GATEWAY_PORT:8012}
eureka:
  client.serviceUrl.defaultZone: http://localhost:${EUREKA_PORT:8010}/eureka
spring:
  application.name: bifrost
  cloud.gateway:
    discovery.locator:
      enabled: true
      lower-case-service-id: true # Allows use of lowercase app name in url request

    # Manual route configuration example
    routes[0]:
      id: users-routing-verification
      uri: lb://mimir-users # 'lb' stands for load-balancer
      predicates[0]: Method=GET
      predicates[1]: Path=/users/verifyRouting
      filters[0]: RemoveRequestHeader=Cookie