server.port: ${API_GATEWAY_PORT:8012}
eureka:
  client.serviceUrl.defaultZone: http://localhost:${DISCOVERY_PORT:8010}/eureka
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
spring:
  application.name: bifrost
  cloud.gateway:
    # Automatic routing configuration
    discovery.locator:
      enabled: true
      lower-case-service-id: true # Allows use of lowercase app name in url requests

    # Manual route configuration example
    routes[0]:
      id: users-service-routing-verification
      uri: lb://mimir-users # 'lb' stands for load-balancer
      predicates[0]: Method=GET
      predicates[1]: Path=/verify/users/routing
      predicates[2]: Header=Authorization, Bearer (.*\..*\..*)  # All predicates must match request for route to be found
      filters[0]: RemoveRequestHeader=Cookie
    # RewritePath example
    routes[1]:
      id: users-service-routing-verification-2
      uri: lb://mimir-users
      predicates[0]: Method=GET
      predicates[1]: Path=/verifyUserSvcRouting
      filters[0]: RemoveRequestHeader=Cookie
      filters[1]: RewritePath=/verifyUserSvcRouting, /verify/users/routing  # RewritePath=/app-name/(?<segment>.*), /*\{segment}